/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWizardRouteImport } from './routes/_authenticated/wizard'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPostGeneratorRouteImport } from './routes/_authenticated/post-generator'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedKeywordsRouteImport } from './routes/_authenticated/keywords'
import { Route as AuthenticatedGmbAnalyticsRouteImport } from './routes/_authenticated/gmb-analytics'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings.integrations'
import { Route as AuthenticatedLibraryImageIdRouteImport } from './routes/_authenticated/library.$imageId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWizardRoute = AuthenticatedWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostGeneratorRoute =
  AuthenticatedPostGeneratorRouteImport.update({
    id: '/post-generator',
    path: '/post-generator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeywordsRoute = AuthenticatedKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGmbAnalyticsRoute =
  AuthenticatedGmbAnalyticsRouteImport.update({
    id: '/gmb-analytics',
    path: '/gmb-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedLibraryImageIdRoute =
  AuthenticatedLibraryImageIdRouteImport.update({
    id: '/$imageId',
    path: '/$imageId',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/gmb-analytics': typeof AuthenticatedGmbAnalyticsRoute
  '/keywords': typeof AuthenticatedKeywordsRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/post-generator': typeof AuthenticatedPostGeneratorRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/upload': typeof AuthenticatedUploadRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/wizard': typeof AuthenticatedWizardRoute
  '/library/$imageId': typeof AuthenticatedLibraryImageIdRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/gmb-analytics': typeof AuthenticatedGmbAnalyticsRoute
  '/keywords': typeof AuthenticatedKeywordsRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/post-generator': typeof AuthenticatedPostGeneratorRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/upload': typeof AuthenticatedUploadRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/wizard': typeof AuthenticatedWizardRoute
  '/library/$imageId': typeof AuthenticatedLibraryImageIdRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/gmb-analytics': typeof AuthenticatedGmbAnalyticsRoute
  '/_authenticated/keywords': typeof AuthenticatedKeywordsRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRouteWithChildren
  '/_authenticated/post-generator': typeof AuthenticatedPostGeneratorRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/_authenticated/wizard': typeof AuthenticatedWizardRoute
  '/_authenticated/library/$imageId': typeof AuthenticatedLibraryImageIdRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/gmb-analytics'
    | '/keywords'
    | '/library'
    | '/post-generator'
    | '/settings'
    | '/upload'
    | '/videos'
    | '/wizard'
    | '/library/$imageId'
    | '/settings/integrations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/gmb-analytics'
    | '/keywords'
    | '/library'
    | '/post-generator'
    | '/settings'
    | '/upload'
    | '/videos'
    | '/wizard'
    | '/library/$imageId'
    | '/settings/integrations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/gmb-analytics'
    | '/_authenticated/keywords'
    | '/_authenticated/library'
    | '/_authenticated/post-generator'
    | '/_authenticated/settings'
    | '/_authenticated/upload'
    | '/_authenticated/videos'
    | '/_authenticated/wizard'
    | '/_authenticated/library/$imageId'
    | '/_authenticated/settings/integrations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wizard': {
      id: '/_authenticated/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof AuthenticatedWizardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-generator': {
      id: '/_authenticated/post-generator'
      path: '/post-generator'
      fullPath: '/post-generator'
      preLoaderRoute: typeof AuthenticatedPostGeneratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keywords': {
      id: '/_authenticated/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof AuthenticatedKeywordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gmb-analytics': {
      id: '/_authenticated/gmb-analytics'
      path: '/gmb-analytics'
      fullPath: '/gmb-analytics'
      preLoaderRoute: typeof AuthenticatedGmbAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/library/$imageId': {
      id: '/_authenticated/library/$imageId'
      path: '/$imageId'
      fullPath: '/library/$imageId'
      preLoaderRoute: typeof AuthenticatedLibraryImageIdRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
  }
}

interface AuthenticatedLibraryRouteChildren {
  AuthenticatedLibraryImageIdRoute: typeof AuthenticatedLibraryImageIdRoute
}

const AuthenticatedLibraryRouteChildren: AuthenticatedLibraryRouteChildren = {
  AuthenticatedLibraryImageIdRoute: AuthenticatedLibraryImageIdRoute,
}

const AuthenticatedLibraryRouteWithChildren =
  AuthenticatedLibraryRoute._addFileChildren(AuthenticatedLibraryRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedGmbAnalyticsRoute: typeof AuthenticatedGmbAnalyticsRoute
  AuthenticatedKeywordsRoute: typeof AuthenticatedKeywordsRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRouteWithChildren
  AuthenticatedPostGeneratorRoute: typeof AuthenticatedPostGeneratorRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedWizardRoute: typeof AuthenticatedWizardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedGmbAnalyticsRoute: AuthenticatedGmbAnalyticsRoute,
  AuthenticatedKeywordsRoute: AuthenticatedKeywordsRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRouteWithChildren,
  AuthenticatedPostGeneratorRoute: AuthenticatedPostGeneratorRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedWizardRoute: AuthenticatedWizardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
