/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWizardRouteImport } from './routes/_authenticated/wizard'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPostStorageRouteImport } from './routes/_authenticated/post-storage'
import { Route as AuthenticatedPostGeneratorRouteImport } from './routes/_authenticated/post-generator'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedKeywordsRouteImport } from './routes/_authenticated/keywords'
import { Route as AuthenticatedGmbOauthCallbackRouteImport } from './routes/_authenticated/gmb-oauth-callback'
import { Route as AuthenticatedGmbAnalyticsRouteImport } from './routes/_authenticated/gmb-analytics'
import { Route as AuthenticatedGeotaggingRouteImport } from './routes/_authenticated/geotagging'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompetitorsRouteImport } from './routes/_authenticated/competitors'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedSocialLinkedinRouteImport } from './routes/_authenticated/social.linkedin'
import { Route as AuthenticatedSocialInstagramRouteImport } from './routes/_authenticated/social.instagram'
import { Route as AuthenticatedSocialFacebookRouteImport } from './routes/_authenticated/social.facebook'
import { Route as AuthenticatedSettingsWebhooksRouteImport } from './routes/_authenticated/settings.webhooks'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings.team'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings.security'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings.integrations'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings.general'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings.appearance'
import { Route as AuthenticatedLibraryImageIdRouteImport } from './routes/_authenticated/library.$imageId'
import { Route as ApiPublicHooksRunAutomationsRouteImport } from './routes/api/public/hooks/run-automations'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWizardRoute = AuthenticatedWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostStorageRoute =
  AuthenticatedPostStorageRouteImport.update({
    id: '/post-storage',
    path: '/post-storage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostGeneratorRoute =
  AuthenticatedPostGeneratorRouteImport.update({
    id: '/post-generator',
    path: '/post-generator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeywordsRoute = AuthenticatedKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGmbOauthCallbackRoute =
  AuthenticatedGmbOauthCallbackRouteImport.update({
    id: '/gmb-oauth-callback',
    path: '/gmb-oauth-callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGmbAnalyticsRoute =
  AuthenticatedGmbAnalyticsRouteImport.update({
    id: '/gmb-analytics',
    path: '/gmb-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGeotaggingRoute = AuthenticatedGeotaggingRouteImport.update({
  id: '/geotagging',
  path: '/geotagging',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompetitorsRoute =
  AuthenticatedCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocialLinkedinRoute =
  AuthenticatedSocialLinkedinRouteImport.update({
    id: '/social/linkedin',
    path: '/social/linkedin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSocialInstagramRoute =
  AuthenticatedSocialInstagramRouteImport.update({
    id: '/social/instagram',
    path: '/social/instagram',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSocialFacebookRoute =
  AuthenticatedSocialFacebookRouteImport.update({
    id: '/social/facebook',
    path: '/social/facebook',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsWebhooksRoute =
  AuthenticatedSettingsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedLibraryImageIdRoute =
  AuthenticatedLibraryImageIdRouteImport.update({
    id: '/$imageId',
    path: '/$imageId',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const ApiPublicHooksRunAutomationsRoute =
  ApiPublicHooksRunAutomationsRouteImport.update({
    id: '/api/public/hooks/run-automations',
    path: '/api/public/hooks/run-automations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/geotagging': typeof AuthenticatedGeotaggingRoute
  '/gmb-analytics': typeof AuthenticatedGmbAnalyticsRoute
  '/gmb-oauth-callback': typeof AuthenticatedGmbOauthCallbackRoute
  '/keywords': typeof AuthenticatedKeywordsRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/post-generator': typeof AuthenticatedPostGeneratorRoute
  '/post-storage': typeof AuthenticatedPostStorageRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/upload': typeof AuthenticatedUploadRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/wizard': typeof AuthenticatedWizardRoute
  '/library/$imageId': typeof AuthenticatedLibraryImageIdRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/settings/webhooks': typeof AuthenticatedSettingsWebhooksRoute
  '/social/facebook': typeof AuthenticatedSocialFacebookRoute
  '/social/instagram': typeof AuthenticatedSocialInstagramRoute
  '/social/linkedin': typeof AuthenticatedSocialLinkedinRoute
  '/api/public/hooks/run-automations': typeof ApiPublicHooksRunAutomationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/geotagging': typeof AuthenticatedGeotaggingRoute
  '/gmb-analytics': typeof AuthenticatedGmbAnalyticsRoute
  '/gmb-oauth-callback': typeof AuthenticatedGmbOauthCallbackRoute
  '/keywords': typeof AuthenticatedKeywordsRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/post-generator': typeof AuthenticatedPostGeneratorRoute
  '/post-storage': typeof AuthenticatedPostStorageRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/upload': typeof AuthenticatedUploadRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/wizard': typeof AuthenticatedWizardRoute
  '/library/$imageId': typeof AuthenticatedLibraryImageIdRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/settings/webhooks': typeof AuthenticatedSettingsWebhooksRoute
  '/social/facebook': typeof AuthenticatedSocialFacebookRoute
  '/social/instagram': typeof AuthenticatedSocialInstagramRoute
  '/social/linkedin': typeof AuthenticatedSocialLinkedinRoute
  '/api/public/hooks/run-automations': typeof ApiPublicHooksRunAutomationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/competitors': typeof AuthenticatedCompetitorsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/geotagging': typeof AuthenticatedGeotaggingRoute
  '/_authenticated/gmb-analytics': typeof AuthenticatedGmbAnalyticsRoute
  '/_authenticated/gmb-oauth-callback': typeof AuthenticatedGmbOauthCallbackRoute
  '/_authenticated/keywords': typeof AuthenticatedKeywordsRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRouteWithChildren
  '/_authenticated/post-generator': typeof AuthenticatedPostGeneratorRoute
  '/_authenticated/post-storage': typeof AuthenticatedPostStorageRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/_authenticated/wizard': typeof AuthenticatedWizardRoute
  '/_authenticated/library/$imageId': typeof AuthenticatedLibraryImageIdRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/settings/webhooks': typeof AuthenticatedSettingsWebhooksRoute
  '/_authenticated/social/facebook': typeof AuthenticatedSocialFacebookRoute
  '/_authenticated/social/instagram': typeof AuthenticatedSocialInstagramRoute
  '/_authenticated/social/linkedin': typeof AuthenticatedSocialLinkedinRoute
  '/api/public/hooks/run-automations': typeof ApiPublicHooksRunAutomationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/automation'
    | '/calendar'
    | '/competitors'
    | '/dashboard'
    | '/geotagging'
    | '/gmb-analytics'
    | '/gmb-oauth-callback'
    | '/keywords'
    | '/library'
    | '/post-generator'
    | '/post-storage'
    | '/settings'
    | '/upload'
    | '/videos'
    | '/wizard'
    | '/library/$imageId'
    | '/settings/appearance'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/team'
    | '/settings/webhooks'
    | '/social/facebook'
    | '/social/instagram'
    | '/social/linkedin'
    | '/api/public/hooks/run-automations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/automation'
    | '/calendar'
    | '/competitors'
    | '/dashboard'
    | '/geotagging'
    | '/gmb-analytics'
    | '/gmb-oauth-callback'
    | '/keywords'
    | '/library'
    | '/post-generator'
    | '/post-storage'
    | '/settings'
    | '/upload'
    | '/videos'
    | '/wizard'
    | '/library/$imageId'
    | '/settings/appearance'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/team'
    | '/settings/webhooks'
    | '/social/facebook'
    | '/social/instagram'
    | '/social/linkedin'
    | '/api/public/hooks/run-automations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/automation'
    | '/_authenticated/calendar'
    | '/_authenticated/competitors'
    | '/_authenticated/dashboard'
    | '/_authenticated/geotagging'
    | '/_authenticated/gmb-analytics'
    | '/_authenticated/gmb-oauth-callback'
    | '/_authenticated/keywords'
    | '/_authenticated/library'
    | '/_authenticated/post-generator'
    | '/_authenticated/post-storage'
    | '/_authenticated/settings'
    | '/_authenticated/upload'
    | '/_authenticated/videos'
    | '/_authenticated/wizard'
    | '/_authenticated/library/$imageId'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/security'
    | '/_authenticated/settings/team'
    | '/_authenticated/settings/webhooks'
    | '/_authenticated/social/facebook'
    | '/_authenticated/social/instagram'
    | '/_authenticated/social/linkedin'
    | '/api/public/hooks/run-automations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksRunAutomationsRoute: typeof ApiPublicHooksRunAutomationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wizard': {
      id: '/_authenticated/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof AuthenticatedWizardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-storage': {
      id: '/_authenticated/post-storage'
      path: '/post-storage'
      fullPath: '/post-storage'
      preLoaderRoute: typeof AuthenticatedPostStorageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-generator': {
      id: '/_authenticated/post-generator'
      path: '/post-generator'
      fullPath: '/post-generator'
      preLoaderRoute: typeof AuthenticatedPostGeneratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keywords': {
      id: '/_authenticated/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof AuthenticatedKeywordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gmb-oauth-callback': {
      id: '/_authenticated/gmb-oauth-callback'
      path: '/gmb-oauth-callback'
      fullPath: '/gmb-oauth-callback'
      preLoaderRoute: typeof AuthenticatedGmbOauthCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gmb-analytics': {
      id: '/_authenticated/gmb-analytics'
      path: '/gmb-analytics'
      fullPath: '/gmb-analytics'
      preLoaderRoute: typeof AuthenticatedGmbAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/geotagging': {
      id: '/_authenticated/geotagging'
      path: '/geotagging'
      fullPath: '/geotagging'
      preLoaderRoute: typeof AuthenticatedGeotaggingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitors': {
      id: '/_authenticated/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AuthenticatedCompetitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social/linkedin': {
      id: '/_authenticated/social/linkedin'
      path: '/social/linkedin'
      fullPath: '/social/linkedin'
      preLoaderRoute: typeof AuthenticatedSocialLinkedinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social/instagram': {
      id: '/_authenticated/social/instagram'
      path: '/social/instagram'
      fullPath: '/social/instagram'
      preLoaderRoute: typeof AuthenticatedSocialInstagramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social/facebook': {
      id: '/_authenticated/social/facebook'
      path: '/social/facebook'
      fullPath: '/social/facebook'
      preLoaderRoute: typeof AuthenticatedSocialFacebookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/webhooks': {
      id: '/_authenticated/settings/webhooks'
      path: '/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof AuthenticatedSettingsWebhooksRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/library/$imageId': {
      id: '/_authenticated/library/$imageId'
      path: '/$imageId'
      fullPath: '/library/$imageId'
      preLoaderRoute: typeof AuthenticatedLibraryImageIdRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/api/public/hooks/run-automations': {
      id: '/api/public/hooks/run-automations'
      path: '/api/public/hooks/run-automations'
      fullPath: '/api/public/hooks/run-automations'
      preLoaderRoute: typeof ApiPublicHooksRunAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedLibraryRouteChildren {
  AuthenticatedLibraryImageIdRoute: typeof AuthenticatedLibraryImageIdRoute
}

const AuthenticatedLibraryRouteChildren: AuthenticatedLibraryRouteChildren = {
  AuthenticatedLibraryImageIdRoute: AuthenticatedLibraryImageIdRoute,
}

const AuthenticatedLibraryRouteWithChildren =
  AuthenticatedLibraryRoute._addFileChildren(AuthenticatedLibraryRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedSettingsWebhooksRoute: typeof AuthenticatedSettingsWebhooksRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedSettingsWebhooksRoute: AuthenticatedSettingsWebhooksRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCompetitorsRoute: typeof AuthenticatedCompetitorsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGeotaggingRoute: typeof AuthenticatedGeotaggingRoute
  AuthenticatedGmbAnalyticsRoute: typeof AuthenticatedGmbAnalyticsRoute
  AuthenticatedGmbOauthCallbackRoute: typeof AuthenticatedGmbOauthCallbackRoute
  AuthenticatedKeywordsRoute: typeof AuthenticatedKeywordsRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRouteWithChildren
  AuthenticatedPostGeneratorRoute: typeof AuthenticatedPostGeneratorRoute
  AuthenticatedPostStorageRoute: typeof AuthenticatedPostStorageRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedWizardRoute: typeof AuthenticatedWizardRoute
  AuthenticatedSocialFacebookRoute: typeof AuthenticatedSocialFacebookRoute
  AuthenticatedSocialInstagramRoute: typeof AuthenticatedSocialInstagramRoute
  AuthenticatedSocialLinkedinRoute: typeof AuthenticatedSocialLinkedinRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCompetitorsRoute: AuthenticatedCompetitorsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGeotaggingRoute: AuthenticatedGeotaggingRoute,
  AuthenticatedGmbAnalyticsRoute: AuthenticatedGmbAnalyticsRoute,
  AuthenticatedGmbOauthCallbackRoute: AuthenticatedGmbOauthCallbackRoute,
  AuthenticatedKeywordsRoute: AuthenticatedKeywordsRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRouteWithChildren,
  AuthenticatedPostGeneratorRoute: AuthenticatedPostGeneratorRoute,
  AuthenticatedPostStorageRoute: AuthenticatedPostStorageRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedWizardRoute: AuthenticatedWizardRoute,
  AuthenticatedSocialFacebookRoute: AuthenticatedSocialFacebookRoute,
  AuthenticatedSocialInstagramRoute: AuthenticatedSocialInstagramRoute,
  AuthenticatedSocialLinkedinRoute: AuthenticatedSocialLinkedinRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksRunAutomationsRoute: ApiPublicHooksRunAutomationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
